name: Build winston (unsigned)

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15 # Xcode 16 is available on macos-15 runners

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Set version number
        run: |
          PROJECT_NAME="winston"
          pbxproj="${PROJECT_NAME}.xcodeproj/project.pbxproj"
          sed -i '' -E 's/(MARKETING_VERSION = )[^;]+;/\169.69.69;/' "$pbxproj"

      - name: Build (unsigned)
        env:
          CODE_SIGNING_ALLOWED: "NO"
          CODE_SIGNING_REQUIRED: "NO"
          CODE_SIGN_IDENTITY: ""
          DEVELOPMENT_TEAM: ""
        run: |
          xcodebuild \
            -scheme "winston" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            clean build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            ONLY_ACTIVE_ARCH=NO | xcpretty

      - name: Package .ipa manually
        run: |
          set -euo pipefail
          APP_PATH="$(xcodebuild -scheme 'winston' -showBuildSettings -configuration Release 2>/dev/null \
            | awk -F' = ' '/TARGET_BUILD_DIR/ {tbd=$2} /WRAPPER_NAME/ {wn=$2} END {print tbd "/" wn}')"

          echo "App built at: $APP_PATH"
          WORK="$RUNNER_TEMP/ipa"
          mkdir -p "$WORK/Payload"
          cp -R "$APP_PATH" "$WORK/Payload/"

          (cd "$WORK" && zip -qry winston-unsigned.ipa Payload)

          mkdir -p "$RUNNER_TEMP/build"
          mv "$WORK/winston-unsigned.ipa" "$RUNNER_TEMP/build/winston-unsigned.ipa"

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: winston-unsigned
          path: ${{ runner.temp }}/build/winston-unsigned.ipa
          retention-days: 7

      - name: Create GitHub Tag
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple
