name: Build winston

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Xcode project
        run: |
          xcodebuild \
            -scheme "winston" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build 2>&1 | tee build.log
        continue-on-error: true

      - name: Create IPA manually
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "winston.app" -path "*/Build/Products/*" | head -1)
          echo "Found app at: $APP_PATH"
          
          if [ -n "$APP_PATH" ]; then
            mkdir -p winston-ipa/Payload
            cp -R "$APP_PATH" winston-ipa/Payload/
            cd winston-ipa
            zip -r winston.ipa Payload/
            cd ..
            echo "✅ IPA created successfully"
          else
            echo "❌ App bundle not found"
            exit 1
          fi

      - name: Display build errors
        run: |
          echo "=== BUILD ERRORS ==="
          if [ -f build.log ]; then
            grep -A 5 -B 5 "error:" build.log || echo "No specific error messages found"
            echo ""
            echo "=== FULL BUILD LOG ==="
            cat build.log
          else
            echo "Build log not found"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winston-build
          path: |
            winston-ipa/winston.ipa
            build.log
          retention-days: 7
