# .github/workflows/ios-unsigned.yml
name: iOS unsigned build
on:
  workflow_dispatch:
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # If the project uses CocoaPods, keep this; otherwise delete this step
      - name: Install CocoaPods
        if: ${{ hashFiles('Podfile') != '' }}
        run: |
          sudo gem install cocoapods --no-document
          pod install --repo-update

      - name: Archive (unsigned)
        run: |
          set -e
          SCHEME="YOUR_SCHEME_NAME"              # <- set this
          WORKSPACE=$(ls *.xcworkspace 2>/dev/null | head -n1)
          ARCHIVE="$PWD/build/App.xcarchive"

          if [ -n "$WORKSPACE" ]; then
            xcodebuild -workspace "$WORKSPACE" \
              -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean archive -archivePath "$ARCHIVE"
          else
            xcodebuild -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean archive -archivePath "$ARCHIVE"
          fi

      - name: Package unsigned IPA
        run: |
          APP_DIR="$PWD/build/App.xcarchive/Products/Applications"
          mkdir -p Payload
          cp -R "$APP_DIR"/*.app Payload/
          zip -qry app-unsigned.ipa Payload
          ls -lah app-unsigned.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: app-unsigned.ipa