name: Build winston
permissions:
    contents: write
    pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Set version number
        run: |
            YOUR_PROJECT_NAME="winston"
            sed -i '' -e 's/MARKETING_VERSION \\= [^\\;]*\\;/MARKETING_VERSION = 69.69.69;/' ${YOUR_PROJECT_NAME}.xcodeproj/project.pbxproj

      - name: Build Xcode project
        run: |
          xcodebuild \
            -scheme "winston" \
            -sdk iphoneos \
            -destination platform=iOS \
            clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: winston-build
          path: |
            winston.xcodeproj/build/
            winston.xcodeproj/derivedData/
          retention-days: 7
