name: iOS unsigned build (static)

on:
  workflow_dispatch:

env:
  USE_WORKSPACE: "false"
  WORKSPACE: "winston.xcworkspace"
  PROJECT:  "winston.xcodeproj"
  SCHEME:   "winston"
  APPICON_NAME: "iconStandard"   # change to any existing *.appiconset

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Archive (unsigned)
        shell: bash
        run: |
          set -euo pipefail
          ARCHIVE_PATH="$PWD/build/App.xcarchive"

          if [[ "${USE_WORKSPACE}" == "true" ]]; then
            xcodebuild -workspace "$WORKSPACE" \
              -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              ASSETCATALOG_COMPILER_APPICON_NAME="$APPICON_NAME" \
              ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS=NO \
              clean archive -archivePath "$ARCHIVE_PATH"
          else
            xcodebuild -project "$PROJECT" \
              -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              ASSETCATALOG_COMPILER_APPICON_NAME="$APPICON_NAME" \
              ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS=NO \
              clean archive -archivePath "$ARCHIVE_PATH"
          fi

      - name: Package unsigned IPA
        run: |
          APP_DIR="$PWD/build/App.xcarchive/Products/Applications"
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_DIR"/*.app Payload/
          zip -qry app-unsigned.ipa Payload
          ls -lah app-unsigned.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: app-unsigned.ipa
          if-no-files-found: error
