name: Build winston
permissions:
    contents: write
    pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Clean Swift Package Manager cache
        run: |
          rm -rf winston.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          rm -rf winston.xcodeproj/project.xcworkspace/xcuserdata/*/xcuserdata/swiftpm/Package.resolved
          xcodebuild -resolvePackageDependencies -scheme winston

      - name: Set version number
        run: |
            YOUR_PROJECT_NAME="winston"
            sed -i '' -e 's/MARKETING_VERSION \\= [^\\;]*\\;/MARKETING_VERSION = 69.69.69;/' ${YOUR_PROJECT_NAME}.xcodeproj/project.pbxproj

      - name: Create export options plist
        run: |
          cat > exportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string></string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Build and Archive Xcode project
        run: |
          # Create archive
          xcodebuild \
            -scheme "winston" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "winston.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive 2>&1 | tee build.log
        continue-on-error: true

      - name: Create IPA from Archive
        run: |
          # Create IPA from archive
          xcodebuild \
            -exportArchive \
            -archivePath "winston.xcarchive" \
            -exportPath "winston-ipa" \
            -exportOptionsPlist exportOptions.plist 2>&1 | tee export.log
        continue-on-error: true

      - name: Verify IPA creation
        run: |
          echo "=== IPA CREATION STATUS ==="
          if [ -f "winston-ipa/winston.ipa" ]; then
            echo "✅ IPA file created successfully"
            ls -la winston-ipa/
          else
            echo "❌ IPA file not found"
            echo "Contents of winston-ipa directory:"
            ls -la winston-ipa/ || echo "Directory does not exist"
          fi

      - name: Find build output location
        run: |
          echo "=== BUILD OUTPUT LOCATION ==="
          find ~/Library/Developer/Xcode/DerivedData -name "winston*" -type d 2>/dev/null | head -5
          echo ""
          echo "=== APP BUNDLE LOCATION ==="
          find ~/Library/Developer/Xcode/DerivedData -name "*.app" -path "*/winston*" 2>/dev/null | head -5

      - name: Display build errors
        run: |
          echo "=== BUILD ERRORS ==="
          if [ -f build.log ]; then
            # Extract and display compilation errors
            grep -A 5 -B 5 "error:" build.log || echo "No specific error messages found"
            echo ""
            echo "=== FULL BUILD LOG ==="
            cat build.log
          else
            echo "Build log not found"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winston-build
          path: |
            winston-ipa/winston.ipa
            winston.xcarchive
            build.log
            export.log
          retention-days: 7
