name: iOS unsigned build (static)

on:
  workflow_dispatch:

env:
  USE_WORKSPACE: "false"
  WORKSPACE: "winston.xcworkspace"
  PROJECT:  "winston.xcodeproj"
  SCHEME:   "winston"
  CATALOG_PATH: "winston/Assets.xcassets"
  APPICON_NAME: "iconStandard"   # <-- set to one of your existing sets
  SKIP_ASSETS: "false"           # set to "true" to bypass assets and confirm build otherwise works

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Show tool versions
        run: |
          xcodebuild -version
          swift --version

      - name: Validate AppIcon set exists
        run: |
          set -euo pipefail
          echo "Using APPICON_NAME=$APPICON_NAME"
          echo "Catalog at $CATALOG_PATH"
          if ! find "$CATALOG_PATH" -type d -name "${APPICON_NAME}.appiconset" | grep -q .; then
            echo "::error ::'${APPICON_NAME}.appiconset' not found in $CATALOG_PATH"
            echo "Available sets:"; find "$CATALOG_PATH" -type d -name "*.appiconset" -printf " - %f\n" || find "$CATALOG_PATH" -type d -name "*.appiconset" -print
            exit 1
          fi

      - name: What does the project think the AppIcon is?
        run: |
          xcodebuild -showBuildSettings -project "$PROJECT" -scheme "$SCHEME" | \
            grep -E "ASSETCATALOG_COMPILER_APPICON_NAME|PRODUCT_BUNDLE_IDENTIFIER|IPHONEOS_DEPLOYMENT_TARGET" || true
          echo "We will override AppIcon to: $APPICON_NAME at build time."

      # Run actool manually for clear error messages (independent of xcodebuild)
      - name: Run actool on full catalog (verbose)
        run: |
          set -euo pipefail
          mkdir -p diagnostics/compiled-full
          xcrun actool "$CATALOG_PATH" \
            --compile diagnostics/compiled-full \
            --platform iphoneos \
            --minimum-deployment-target 18.0 \
            --app-icon "$APPICON_NAME" \
            --output-partial-info-plist diagnostics/asset-info.plist \
            --errors --warnings --notices --verbose \
            > diagnostics/actool-full.log 2>&1 || true

          echo "==== actool (first 200 lines) ===="
          sed -n '1,200p' diagnostics/actool-full.log || true
          echo "==== end actool preview ===="

          if grep -Eiq '(^|\s)error:' diagnostics/actool-full.log; then
            echo "::error ::actool reported errors. See artifact 'asset-diagnostics'."
          fi

      - name: Upload asset diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: asset-diagnostics
          path: diagnostics
          if-no-files-found: ignore

      - name: Archive (unsigned)
        shell: bash
        run: |
          set -euo pipefail
          ARCHIVE_PATH="$PWD/build/App.xcarchive"

          # Optionally skip assets entirely to confirm the rest of the build is OK
          SKIP_FLAG=()
          if [[ "${SKIP_ASSETS}" == "true" ]]; then
            echo "⚠️  ASSETCATALOG_COMPILER_SKIP_ASSETS=YES enabled"
            SKIP_FLAG+=(ASSETCATALOG_COMPILER_SKIP_ASSETS=YES)
          else
            SKIP_FLAG+=(ASSETCATALOG_COMPILER_APPICON_NAME="$APPICON_NAME")
          fi

          if [[ "${USE_WORKSPACE}" == "true" ]]; then
            xcodebuild -workspace "$WORKSPACE" \
              -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              "${SKIP_FLAG[@]}" \
              clean archive -archivePath "$ARCHIVE_PATH"
          else
            xcodebuild -project "$PROJECT" \
              -scheme "$SCHEME" -configuration Release \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              "${SKIP_FLAG[@]}" \
              clean archive -archivePath "$ARCHIVE_PATH"
          fi

      - name: Package unsigned IPA
        run: |
          APP_DIR="$PWD/build/App.xcarchive/Products/Applications"
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_DIR"/*.app Payload/
          zip -qry app-unsigned.ipa Payload
          ls -lah app-unsigned.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: app-unsigned.ipa
          if-no-files-found: error
